### ISSUE TITLE
Warning is not displayed on start of sublime text with file-parameter

### ISSUE THREAD

**Issue by arberg** [titoBouzout/LineEndings#10]
If executed as
C:\Tools\SublimeText\sublime_text.exe <filename>
then warning is not displayed when sublimeText is closed. This is how I run sublime text on files, because I click files from Total Commander, and I have sublimeText auto-close on close of last file, so this frequently happens for me. If sublime text is open in the background, when executing command, then the warning is displayed.

Best Alex

PS: Nice tool by the way :)

**Comment by titoBouzout** [comment]
Thanks
