### ISSUE TITLE
anyway to display line ending in status bar?

### ISSUE THREAD

**Issue by fyears** [titoBouzout/LineEndings#12]
it seems that the old version for subl 2 supports

```
{
    "show_line_endings_on_status_bar": true
}
```

But I update the plugin today in subl 3, this setting doesn't work.

**Comment by fyears** [comment]
Well, I immediately searched a solution from [here](http://simbo.github.io/2014/03/optional-satus-bar-elements-in-sublime-text-3.html).

The built-in setting in sublime text 3 supports this setting:

```
{
    "show_line_endings": true
}
```

**Comment by ckib16** [comment]
Just a comment from someone new to the plugin - @fyears solution did indeed work. However, it definitely wasn't obvious to me from reading the readme installation directions that I would have to enable this setting.

Maybe add the text below to the Installations section for more clarity on HOW to ensure ST3 has enabled this?:

## Installation

Download or clone the contents of this repository to a folder named exactly as the package name into the Packages/ folder of ST.

To show line ending in status bar, add the following to ST3 preferences (Preferences > Settings - User)
```
{
    "show_line_endings": true
}
```
