### ISSUE TITLE
Line endings alert too intrusive

### ISSUE THREAD

**Issue by rchl** [titoBouzout/LineEndings#3]
Warning about unwanted line endings sounds like an useful feature but the way it's implemented (message box blocking whole application) is too intrusive for it to be useful.
I'm not sure what would be a better way to do it. Maybe showing a marker in the gutter would be enough. There is a risk of it being too subtle though...

**Comment by titoBouzout** [comment]
I think the point of the alert is to be intrusive, if you don't want it to be intrusive then you can just take a look to the status bar that tells which line ending you are using.
